sudo: required
dist: trusty
language: python
python:
    - "3.5"
before_install:
  - sudo add-apt-repository ppa:jon-hedgerows/ffmpeg-backports -y
  - sudo apt-get update -q
  - sudo apt-get install ffmpeg -y
install: make install
script: make test
