version: '3.5'

volumes:
    website_db:
    processmedia2_data:
    logs:
    mosquitto_data:

services:
    nginx:
        image: karakara/nginx
        build:
            context: ./nginx
        ports:
            - "127.0.0.1:${PORT_NGINX}:80"
        volumes:
            - logs:/logs
            - ${PATH_HOST_processed}:/media/processed:ro
        links:
            - website
            - mosquitto
            - player2
            - browser2
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.karakara.rule=Host(`${HOSTNAME}`)"

    website:
        image: karakara/website
        build:
            context: ./website
        env_file:
            - .env
        links:
            - postgres
            - redis
            - mosquitto
        volumes:
            - logs:/logs
            - ${PATH_HOST_source}:/media/source:ro  # The Community interface writes to this location, not too happy about this. Will discuss this with content creators.
            - ${PATH_HOST_meta}:/media/meta:ro

    mosquitto:
        image: karakara/mosquitto
        build:
            context: ./mosquitto
        volumes:
            - mosquitto_data:/mosquitto/data

    player2:
        image: karakara/player2
        build:
            context: ./player2

    browser2:
        image: karakara/browser2
        build:
            context: ./browser2

    postgres:
        image: karakara/postgres
        build:
            context: ./postgres
        volumes:
            - website_db:/var/lib/postgresql/data

    redis:
        image: redis

    processmedia2:
        image: karakara/processmedia2
        profiles:
            - processmedia
        build:
            context: ./processmedia2
        links:
            - website
        env_file:
            - .env
        volumes:
            - logs:/logs
            - processmedia2_data:/processmedia2/data
            - ${PATH_HOST_source}:/media/source:ro
            - ${PATH_HOST_meta}:/media/meta:rw
            - ${PATH_HOST_processed}:/media/processed:rw

        # Force import
        #docker-compose exec processmedia2 /bin/bash
        #root@245ee075bf91:/processmedia2# python3 import_media.py  --config config.docker.json --force

# docker-compose run --rm processmedia2 bash
# docker run -it --rm --entrypoint bash -v //C//Users/calal/code/personal/KaraKara/processmedia2/tests/source:/tmp/workdir jrottenberg/ffmpeg
