volumes:
    logs:
    mqtt_data:
    queue_data:

networks:
    default:
        name: karakara_default
        external: ${EXTERNAL_NETWORK}

services:

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        mem_limit: 1g
        ports:
            - "127.0.0.1:${PORT_NGINX}:80"
        volumes:
            - logs:/logs
            - ${PATH_HOST_processed}:/media/processed:ro
            - ${PWD}/tools/:/static/tools/:ro
            - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - queue_data:/data/queue/:ro
            #- ${PWD}/nginx/logrotate.conf:/etc/logrotate.d/nginx:ro
        links:
            - api_queue
            - mqtt
            - player3
            - browser3
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.karakara.rule=Host(`${HOSTNAME}`)"
            - "traefik.http.routers.karakara.middlewares=kkredir"
            - "traefik.http.middlewares.kkredir.redirectregex.regex=^https://karakara.uk/$$"
            - "traefik.http.middlewares.kkredir.redirectregex.replacement=https://karakara.uk/browser3/"

    api_queue:
        build:
            context: ./api_queue
        restart: unless-stopped
        mem_limit: 1g
        environment:
            SANIC_MQTT: mqtt
            SANIC_PATH_TRACKS: /media/processed/tracks.json  # TODO: same as `processmedia2/config.docker.json` - consider from ENV?
            SANIC_PATH_QUEUE: /data/queue/   # See volumes below
        #ports:  # for local dev
        #    - 8000:8000
        links:
            - mqtt
        volumes:
            - ${PATH_HOST_processed}:/media/processed:ro
            - logs:/logs
            - queue_data:/data/queue/:rw
            #- ${PWD}/api_queue/:/app/:ro   # local dev testing only

    mqtt:
        image: eclipse-mosquitto
        restart: unless-stopped
        mem_limit: 1g
        volumes:
            - mqtt_data:/mosquitto/data
            - ${PWD}/mqtt/:/mosquitto/config/:ro

    player3:
        build:
            context: ./player3
        restart: unless-stopped
        mem_limit: 1g

    browser3:
        build:
            context: ./browser3
        restart: unless-stopped
        mem_limit: 1g

    processmedia3:
        profiles:
            - processmedia3
        build:
            context: ./processmedia3
        restart: unless-stopped
        mem_limit: 8g
        volumes:
            - logs:/logs
            - ${PATH_HOST_source}:/media/source:ro
            - ${PATH_HOST_processed}:/media/processed:rw

    syncthing:
        profiles:
            - syncthing
        image: syncthing/syncthing
        restart: unless-stopped
        mem_limit: 1g
        cpu_count: 1
        hostname: karakara
        environment:
            PUID: 1002
            PGID: 1003
            UMASK: 002
        volumes:
            - ${PWD}/media:/var/syncthing
        ports:
            - 127.0.0.1:8384:8384 # Web UI
            - 22000:22000/tcp # TCP file transfers
            - 22000:22000/udp # QUIC file transfers
            - 21027:21027/udp # Receive local discovery broadcasts
