version: '3.5'

volumes:
    website_db:
    processmedia2_data:
    logs:
    influxdb_data:

services:
    website:
        image: karakara/website
        build:
            context: ./website
        env_file:
            - .env
        environment:
            STATIC_PROCESSMEDIA2_LOG: /logs/processmedia2-app.log
            SQLALCHEMY_URL: postgresql+pypostgresql://karakara:karakara@postgres/karakara
            CACHE_BACKEND: dogpile.cache.redis
            CACHE_BACKEND_ARGUMENTS: '{"host": "redis", "port": 6379} -> json'
            STATIC_PATH_SOURCE: /media/source
            STATIC_PATH_META: /media/meta
            #STATIC_PATH_PROCESSED: /media/processed
            #SESSION_SECRET: change_me
            KARAKARA_CONTAINER_NAME_postgres: 'postgres'
            KARAKARA_WEBSOCKET_HOST: 'websocket'
        links:
            - postgres
            - redis
            - websocket
        volumes:
            - logs:/logs
            - ${PATH_HOST_source}:/media/source:ro  # The Community interface writes to this location, not too happy about this. Will discuss this with content creators.
            - ${PATH_HOST_meta}:/media/meta:ro
            - ${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:ro

    websocket:
        image: karakara/websocket
        build:
            context: ./websocket
        volumes:
            - logs:/logs

    player2:
        image: karakara/player2
        build:
            context: ./player2
        volumes:
            - logs:/logs

    browser2:
        image: karakara/browser2
        build:
            context: ./browser2
        volumes:
            - logs:/logs

    postgres:
        image: karakara/postgres
        build:
            context: ./postgres
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - logs:/logs
            - website_db:/var/lib/postgresql

    redis:
        image: redis

    nginx:
        image: karakara/nginx
        build:
            context: ./nginx
        env_file:
            - .env
        ports:
            - "127.0.0.1:${PORT_NGINX}:80"
        volumes:
            - logs:/logs
            - ${PATH_HOST_processed}:/media/processed:ro
        links:
            - website
            - websocket
            - player2
            - browser2

    processmedia2:
        image: karakara/processmedia2
        build:
            context: ./processmedia2
        links:
            - website
        env_file:
            - .env
        volumes:
            - logs:/logs
            - processmedia2_data:/processmedia2/data
            - ${PATH_HOST_source}:/media/source:ro
            - ${PATH_HOST_meta}:/media/meta:rw
            - ${PATH_HOST_processed}:/media/processed:rw
        environment:
            KARAKARA_PROCESSMEDIA2_ENABLED: ${KARAKARA_PROCESSMEDIA2_ENABLED:-true}
            KARAKARA_RESCAN_INTERVAL_SECONDS: 600
            KARAKARA_PROCESSMEDIA2_CONFIG: config.docker.json
            KARAKARA_PROCESSMEDIA2_CLEANUP: 'false'
            KARAKARA_CONTAINER_NAME_website: 'website'

        # Force import
        #docker-compose exec processmedia2 /bin/bash
        #root@245ee075bf91:/processmedia2# python3 import_media.py  --config config.docker.json --force

    dashboard:
        image: karakara/dashboard
        build:
            context: ./dashboard
        volumes:
            - logs:/logs
            - influxdb_data:/root/.influxdbv2
        ports:
            - "127.0.0.1:${PORT_DASHBOARD}:9999"

# docker-compose run --rm processmedia2 bash
# docker run -it --rm --entrypoint bash -v //C//Users/calal/code/personal/KaraKara/processmedia2/tests/source:/tmp/workdir jrottenberg/ffmpeg
