version: '3.5'

volumes:
    website_db:
    website_data_1:
    website_data_2:

services:

    website:
        build:
            context: ./docker
            dockerfile: python.Dockerfile
            #image: python3_virtualenv
        env_file:
            - .env
        expose:
            - ${PORT_WEBSITE}
        ports:
            - ${KARAKARA_WEBSOCKET_PORT}:${KARAKARA_WEBSOCKET_PORT}
            #- ${PORT_WEBSITE}:${PORT_WEBSITE}
        environment:
            - PORT_WEBSITE
            - KARAKARA_WEBSOCKET_PORT
        links:
            - postgres
        volumes:
            - ./:${PATH_CONTAINER_REPO}:ro
            - ${PATH_HOST_MEDIA}:${PATH_CONTAINER_MEDIA}:ro
            - ${PATH_HOST_MEDIA}/source:${PATH_CONTAINER_MEDIA}/source:rw  # The Community interface writes to this location, not too happy about this. Will discuss this with content creators.
            - website_data_1:${PATH_CONTAINER_WEBSITE}/data:rw
            - website_data_2:${PATH_CONTAINER_WEBSITE}/KaraKara.egg-info:rw
            - ${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:${LOGIN_GOOGLE_CLIENT_SECRET_FILE}:ro
            #- ./production.inidiff:${PATH_CONTAINER_WEBSITE}/data/config/production.inidiff:ro  # Use .env vars with KARAKARA_SETTINGS_KEY=[00:01:00, 00:02:00] -> timedelta instead
        command: make run_production --directory ${PATH_CONTAINER_WEBSITE}

    player2:
        build:
            context: ./player2
            dockerfile: Dockerfile

    postgres:
        image: postgres:9-alpine
        volumes:
            - website_db:/var/lib/postgresql
            - ./docker/postgres:/docker-entrypoint-initdb.d:ro

    nginx:
        image: nginx:mainline-alpine
        environment:
            - PORT_NGINX
            - PORT_WEBSITE
        env_file:
            - .env
        ports:
            - "${PORT_NGINX}:${PORT_NGINX}"
        volumes:
            - ./docker/nginx.conf:/tmp/nginx.conf:ro
            - ./:${PATH_CONTAINER_REPO}:ro
            - ${PATH_HOST_MEDIA}:${PATH_CONTAINER_MEDIA}:ro
            - website_data_1:${PATH_CONTAINER_WEBSITE}/data:ro
        links:
            - website
            - player2
        command: /bin/sh -c "DOLLAR='$$' envsubst < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
