
services:
  test_cypress:
    image: cypress/included:9.4.1
    working_dir: /tests
    volumes:
      # USER passthrough
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # mount tests - readonly
      - ${PWD}/test_cypress/cypress.json:/tests/cypress.json:ro
      - ${PWD}/test_cypress/cypress:/tests/cypress:ro
      # mount reports - writeable
      - ${PWD}/test_cypress/reports:/tests/reports:rw
    entrypoint: ["cypress"]
    command: ["run"]

    #
    #links:
    #    - nginx
    #environment:
      #- DISPLAY
      #- CYPRESS_BASE_URL=http://client:8001/?api=http://server:8000
    #user: ${USER}  # ummm, problems with user on cypress startup

