version: '3.5'

volumes:
    website_data_1:
    website_data_2:

services:

    test_web:
        build:
            context: ./docker
            dockerfile: python.Dockerfile
        env_file:
            - .env
        volumes:
            - ./:${PATH_CONTAINER_REPO}:ro
            - website_data_1:${PATH_CONTAINER_WEBSITE}/data:rw
            - website_data_2:${PATH_CONTAINER_WEBSITE}/KaraKara.egg-info:rw
        command: make test --directory ${PATH_CONTAINER_WEBSITE}

    #test_processmedia2:
        #todo
