version: '3.5'

volumes:
  processmedia2_data:

services:

  processmedia2:
    build:
      context: ./docker
      dockerfile: processmedia2.base.dockerfile
    environment:
        - PATH_HOST_source
        - PATH_HOST_meta
        - PATH_HOST_processed
    env_file:
        - .env
    volumes:
      - .:/processmedia2:ro
      - processmedia2_data:/processmedia2/data
      - ${PATH_HOST_source}:${PATH_CONTAINER_MEDIA}/source:ro
      - ${PATH_HOST_meta}:${PATH_CONTAINER_MEDIA}/meta:rw
      - ${PATH_HOST_processed}:${PATH_CONTAINER_MEDIA}/processed:rw
    environment:
      KARAKARA_PROCESSMEDIA2_ENABLED: ${KARAKARA_PROCESSMEDIA2_ENABLED:-true}
      KARAKARA_RESCAN_INTERVAL_SECONDS: 600
      KARAKARA_PROCESSMEDIA2_CONFIG: config.docker.json
      KARAKARA_PROCESSMEDIA2_CLEANUP: 'false'
    command: ./docker-compose.yml.processmedia2.sh
    # command: [
    #   'pytest',
    #   'processmedia_libs',
    #   'tests',
    #   '--doctest-modules',
    #   '--pdb',
    #   '-x',
    #   #'-k', 'test_get_image_from_video'
    # ]
    #command: ['make', 'test']

# docker-compose run --rm processmedia2 bash
# docker run -it --rm --entrypoint bash -v //C//Users/calal/code/personal/KaraKara/processmedia2/tests/source:/tmp/workdir jrottenberg/ffmpeg