version: '3.5'

volumes:
  processmedia2_data:

services:

  #ffmpeg:
  #  image: jrottenberg/ffmpeg

  processmedia2:
    build:
      context: ./docker
      dockerfile: processmedia2.base.dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- processmedia2_data:/processmedia2/data
      - .:/processmedia2:ro
      # osx and linux can mount absolute paths in the same place - making containers consistent - windows this cant be done - this is my best attempt at a readable solution
      #- ${PATH_HOST_source}:/PATH_HOST_source:ro
      #- ${PATH_HOST_meta}:/PATH_HOST_meta:rw
      #- ${PATH_HOST_processed}:/PATH_HOST_processed:rw
    environment:
      KARAKARA_PROCESSMEDIA2_ENABLED: ${KARAKARA_PROCESSMEDIA2_ENABLED:-true}
      KARAKARA_RESCAN_INTERVAL_SECONDS: 600
      KARAKARA_PROCESSMEDIA2_CONFIG: config.docker.json
      KARAKARA_PROCESSMEDIA2_CLEANUP: 'false'
    #  PATH_HOST_REPO: $PATH_HOST
      #PATH_HOST_TEMP: ${HOME}/temp
      #PATH_HOST_source: ${PATH_HOST_source}
      #PATH_HOST_meta: ${PATH_HOST_meta}
      #PATH_HOST_processed: ${PATH_HOST_processed}
    # command: [
    #   'pytest',
    #   'processmedia_libs',
    #   'tests',
    #   '--doctest-modules',
    #   '--pdb',
    #   '-x',
    #   #'-k', 'test_get_image_from_video'
    # ]
    #command: ['make', 'test']

# docker-compose run --rm processmedia2 bash
# docker run -it --rm --entrypoint bash -v //C//Users/calal/code/personal/KaraKara/processmedia2/tests/source:/tmp/workdir jrottenberg/ffmpeg