# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "precise32"

  config.vm.provision :shell, :path => "vagrant_bootstrap.sh"

  config.vm.network :forwarded_port, host:   25, guest: 25
  config.vm.network :forwarded_port, host:   80, guest: 80
  config.vm.network :forwarded_port, host: 6543, guest: 6543
  config.vm.network :forwarded_port, host: 9873, guest: 9873

  config.vm.provider "virtualbox" do |v|
    v.name = "karakara"
    v.customize ["modifyvm", :id, "--memory", "512"]
    # TODO
    #  - Setup LAN_IP and ports to forward in Vagrantfile
  end

end
