# generated by datamodel-codegen:
#   filename:  components.yaml

from pydantic import AwareDatetime, BaseModel, Field


class Attachment(BaseModel):
    variant: str = Field(..., description="Attachment variant name")
    mime: str = Field(..., description="MIME type of the attachment")
    path: str = Field(..., description="Path to the attachment file")


class Subtitle(BaseModel):
    start: float = Field(..., description="Start time in seconds")
    end: float = Field(..., description="End time in seconds")
    text: str = Field(..., description="Subtitle text content")
    top: bool = Field(..., description="Whether subtitle appears at top of screen")


class QueueItem(BaseModel):
    id: int = Field(..., description="Unique queue item identifier")
    track_id: str = Field(..., description="ID of the track in the queue")
    track_duration: float = Field(..., description="Track duration in seconds")
    session_id: str = Field(..., description="Session ID of the user who added this item")
    performer_name: str = Field(..., description="Name of the performer")
    start_time: float | None = Field(
        ..., description="Unix timestamp when the track starts playing (null if not yet scheduled)"
    )
    video_variant: str = Field(..., description="Selected video variant")
    subtitle_variant: str = Field(..., description="Selected subtitle variant")


class Settings(BaseModel):
    title: str = Field(..., max_length=16, min_length=1, title="Room title")
    track_space: float = Field(..., ge=0.0, le=60.0, title="Gap between tracks (seconds)")
    hidden_tags: list[str] = Field(..., title="Tags to hide from display")
    forced_tags: list[str] = Field(..., title="Tags that must be present")
    preview_volume: float = Field(..., ge=0.0, le=1.0, multiple_of=0.01, title="Preview playback volume")
    coming_soon_track_count: int = Field(..., ge=1, le=9, title="Number of upcoming tracks to show publicly")
    validation_event_start_datetime: AwareDatetime | None = Field(..., title="Event start time")
    validation_event_end_datetime: AwareDatetime | None = Field(..., title="Event end time")
    auto_reorder_queue: bool = Field(..., title="Auto-Reorder Queue")


class Attachments(BaseModel):
    video: list[Attachment]
    image: list[Attachment]
    subtitle: list[Attachment]


class Track(BaseModel):
    id: str = Field(..., description="Unique track identifier")
    duration: float = Field(..., description="Track duration in seconds")
    tags: dict[str, list[str]] = Field(..., description="Key-value tags for the track")
    attachments: Attachments
