#!/usr/bin/python

import os
import sys
import socket

from dnslib import A, AAAA, CNAME, MX, RR, TXT
from dnslib import DNSHeader, DNSRecord, QTYPE


def main(args):
    if len(args) != 3:
        print "Usage: %s [address to listen] [address to serve]"
        return 1

    address = sys.argv[2]

    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
    s.bind((sys.argv[1], 53))

    os.setgid(1000)
    os.setuid(1000)

    while True:
        try:
            data, peer = s.recvfrom(8192)

            request = DNSRecord.parse(data)
            reply = DNSRecord(DNSHeader(id=request.header.id, qr=1, aa=1, ra=1), q=request.q)
            reply.add_answer(RR(request.q.qname, request.q.qtype, rdata=A(address)))

            s.sendto(reply.pack(), peer)
            print "Responded to %s's request for %s" % (peer[0], request.q.qname)
        except Exception as e:
            print e


if __name__ == "__main__":
    sys.exit(main(sys.argv))
