# generated by datamodel-codegen:
#   filename:  components.yaml

from typing import NotRequired, TypedDict


class Attachment(TypedDict):
    variant: str
    mime: str
    path: str


class Subtitle(TypedDict):
    start: float
    end: float
    text: str
    top: bool


class QueueItem(TypedDict):
    id: int
    track_id: str
    track_duration: float
    session_id: str
    performer_name: str
    start_time: float | None
    video_variant: str
    subtitle_variant: str


class Settings(TypedDict):
    title: str
    track_space: float
    hidden_tags: list[str]
    forced_tags: list[str]
    preview_volume: float
    coming_soon_track_count: int
    validation_event_start_datetime: str | None
    validation_event_end_datetime: str | None
    auto_reorder_queue: bool


class LintError(TypedDict):
    track_id: str
    file: NotRequired[str | None]
    message: str


class User(TypedDict):
    is_admin: bool


class Attachments(TypedDict):
    video: list[Attachment]
    image: list[Attachment]
    subtitle: list[Attachment]


class Track(TypedDict):
    id: str
    duration: float
    tags: dict[str, list[str]]
    attachments: Attachments
    sources: NotRequired[list[str]]
