# generated by datamodel-codegen:
#   filename:  components.yaml

from typing import NotRequired, TypedDict


class Attachment(TypedDict):
    variant: str
    mime: str
    path: str


class Subtitle(TypedDict):
    start: float
    end: float
    text: str
    top: bool


class QueueItem(TypedDict):
    id: int
    track_id: str
    track_duration: float
    session_id: str
    performer_name: str
    start_time: float | None
    video_variant: str
    subtitle_variant: str


class Settings(TypedDict):
    title: NotRequired[str]
    track_space: NotRequired[float]
    track_query: NotRequired[str | None]
    preview_volume: NotRequired[float]
    coming_soon_track_count: NotRequired[int]
    validation_event_start_datetime: NotRequired[str | None]
    validation_event_end_datetime: NotRequired[str | None]
    auto_reorder_queue: NotRequired[bool]


class Attachments(TypedDict):
    video: list[Attachment]
    image: list[Attachment]
    subtitle: list[Attachment]


class Track(TypedDict):
    id: str
    duration: float
    tags: dict[str, list[str]]
    attachments: Attachments
