help:
	#

install: lib.js jquery.min.js

lib.js:
	ln -s ../website/karakara/static/js/lib.js

jquery.min.js:
	ln -s ../website/data/externals/static/jquery.min.js

build:
	# TODO

test:
	# TODO

clean:
	rm -rf lib.js jquery.min.js
