
class QUEUE_DUPLICATE():
    NONE = None
    THRESHOLD = 'THRESHOLD'
    PLAYED = 'PLAYED'
    PENDING = 'PENDING'
    PERFORMER = 'PERFORMER'


class TOKEN_ISSUE_ERROR(object):
    NONE = None
    EVENT_END = 'EVENT_END'
    TOKEN_LIMIT = 'TOKEN_LIMIT'
    TOKEN_ISSUED = 'TOKEN_ISSUED'

