/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Track: {
            /** @description Unique track identifier */
            id: string;
            /**
             * Format: float
             * @description Track duration in seconds
             */
            duration: number;
            /** @description Key-value tags for the track */
            tags: {
                [key: string]: string[];
            };
            attachments: {
                video: components["schemas"]["Attachment"][];
                image: components["schemas"]["Attachment"][];
                subtitle: components["schemas"]["Attachment"][];
            };
            /** @description List of source files for the track */
            sources?: string[];
        };
        Attachment: {
            /** @description Attachment variant name */
            variant: string;
            /** @description MIME type of the attachment */
            mime: string;
            /** @description Path to the attachment file */
            path: string;
        };
        Subtitle: {
            /**
             * Format: float
             * @description Start time in seconds
             */
            start: number;
            /**
             * Format: float
             * @description End time in seconds
             */
            end: number;
            /** @description Subtitle text content */
            text: string;
            /**
             * @description Whether subtitle appears at top of screen
             * @default false
             */
            top: boolean;
        };
        QueueItem: {
            /** @description Unique queue item identifier */
            id: number;
            /** @description ID of the track in the queue */
            track_id: string;
            /**
             * Format: float
             * @description Track duration in seconds
             */
            track_duration: number;
            /** @description Session ID of the user who added this item */
            session_id: string;
            /** @description Name of the performer */
            performer_name: string;
            /**
             * Format: float
             * @description Unix timestamp when the track starts playing (null if not yet scheduled)
             */
            start_time: number | null;
            /** @description Selected video variant */
            video_variant: string;
            /** @description Selected subtitle variant */
            subtitle_variant: string;
        };
        Settings: {
            /**
             * Room title
             * @description What to show on the splash screen while waiting for people to queue some tracks
             * @default KaraKara
             */
            title: string;
            /**
             * Gap between tracks (seconds)
             * Format: float
             * @description The time between finishing one track and auto-playing the next, to give people time to get on and off stage
             * @default 15
             */
            track_space: number;
            /**
             * Tags to hide from display
             * @description Tracks with these tags won't be visible for users to select, unless there are other tags (eg if a track is tagged both "anime" and "cartoon", hiding the "anime" tag will still show the track in the "cartoon" category)
             * @default []
             */
            hidden_tags: string[];
            /**
             * Tags that must be present
             * @description Only tracks with these tags will be visible for the users to select
             * @default []
             */
            forced_tags: string[];
            /**
             * Preview volume
             * Format: float
             * @description The volume of the screen in-between tracks
             * @default 0.1
             */
            preview_volume: number;
            /**
             * "Coming soon" track count
             * @description Show the exact order for the next N tracks, and obfuscate the rest of the queue to give admins more leeway to re-order the queue
             * @default 5
             */
            coming_soon_track_count: number;
            /**
             * Event start time
             * Format: date-time
             * @description Prevent users from adding tracks until this time
             * @default null
             */
            validation_event_start_datetime: string | null;
            /**
             * Event end time
             * Format: date-time
             * @description Prevent users from adding tracks after this time
             * @default null
             */
            validation_event_end_datetime: string | null;
            /**
             * Auto-Reorder Queue
             * @description Balance the queue by giving priority to first-time singers
             * @default false
             */
            auto_reorder_queue: boolean;
        };
        LintError: {
            /** @description ID of the track with an error */
            track_id: string;
            /** @description File path related to the error */
            file?: string | null;
            /** @description Error message */
            message: string;
        };
        User: {
            /**
             * @description Whether the user has admin privileges
             * @default false
             */
            is_admin: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Track = components['schemas']['Track'];
export type Attachment = components['schemas']['Attachment'];
export type Subtitle = components['schemas']['Subtitle'];
export type QueueItem = components['schemas']['QueueItem'];
export type Settings = components['schemas']['Settings'];
export type LintError = components['schemas']['LintError'];
export type User = components['schemas']['User'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
