/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Track: {
            /** @description Unique track identifier */
            id: string;
            /**
             * Format: float
             * @description Track duration in seconds
             */
            duration: number;
            /** @description Key-value tags for the track */
            tags: {
                [key: string]: string[];
            };
            attachments: {
                video: components["schemas"]["Attachment"][];
                image: components["schemas"]["Attachment"][];
                subtitle: components["schemas"]["Attachment"][];
            };
        };
        Attachment: {
            /** @description Attachment variant name */
            variant: string;
            /** @description MIME type of the attachment */
            mime: string;
            /** @description Path to the attachment file */
            path: string;
        };
        Subtitle: {
            /**
             * Format: float
             * @description Start time in seconds
             */
            start: number;
            /**
             * Format: float
             * @description End time in seconds
             */
            end: number;
            /** @description Subtitle text content */
            text: string;
            /**
             * @description Whether subtitle appears at top of screen
             * @default false
             */
            top: boolean;
        };
        QueueItem: {
            /** @description Unique queue item identifier */
            id: number;
            /** @description ID of the track in the queue */
            track_id: string;
            /**
             * Format: float
             * @description Track duration in seconds
             */
            track_duration: number;
            /** @description Session ID of the user who added this item */
            session_id: string;
            /** @description Name of the performer */
            performer_name: string;
            /** @description Unix timestamp when the track starts playing (null if not yet scheduled) */
            start_time: number | null;
            /** @description Selected video variant */
            video_variant: string;
            /** @description Selected subtitle variant */
            subtitle_variant: string;
        };
        Settings: {
            /**
             * @description Room title
             * @default KaraKara
             */
            title: string;
            /**
             * Format: float
             * @description Gap between tracks (seconds)
             * @default 15
             */
            track_space: number;
            /**
             * @description Tags to hide from display
             * @default [
             *       "red:duplicate"
             *     ]
             */
            hidden_tags: string[];
            /**
             * @description Tags that must be present
             * @default []
             */
            forced_tags: string[];
            /**
             * Format: float
             * @description Preview playback volume (0.0 - 1.0)
             * @default 0.1
             */
            preview_volume: number;
            /**
             * @description Number of upcoming tracks to show publicly
             * @default 5
             */
            coming_soon_track_count: number;
            /** @description Event start time */
            validation_event_start_datetime?: string | null;
            /** @description Event end time */
            validation_event_end_datetime?: string | null;
            /**
             * @description Whether to automatically reorder the queue
             * @default false
             */
            auto_reorder_queue: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Track = components['schemas']['Track'];
export type Attachment = components['schemas']['Attachment'];
export type Subtitle = components['schemas']['Subtitle'];
export type QueueItem = components['schemas']['QueueItem'];
export type Settings = components['schemas']['Settings'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
