volumes:
  redis_data:

services:

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data:rw
    #ports:
    #  - 6379:6379

  mqtt:
    image: eclipse-mosquitto
    #ports:
    #  - 1883:1883

  api_queue:
    build:
      context: ./
      target: test
    ports:
      - 1337:1337
    links:
      - redis
      - mqtt
    volumes:
      - ${PWD}:/app/:ro
