# for solo dev-testings api_queue
# uner normal use, use the Dockerfile in the root of the project

volumes:
  queue_data:
  mosquitto_data:

services:

  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - mosquitto_data:/mosquitto/data
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  api_queue:
    build:
      context: ./
      target: test
    ports:
      - 8000:8000
    links:
      - mqtt
    volumes:
      - ${PWD}:/app/:ro
      #- ${PWD}/tests/tracks.json:/app/tracks.json:ro
      - queue_data:/data/queue/:rw
    environment:
        SANIC_MQTT: mqtt
        SANIC_PATH_TRACKS: /app/tests/tracks.json
        SANIC_PATH_QUEUE: /data/queue/
