[project]
name = "api_queue"
version = "0.0.0"
readme = "README.md"
dependencies = [
	"sanic",
	"sanic-ext",
	"sanic-openapi",
	"ujson",
	# aiomqtt is now on version 2.x.x `.connect()` is no longer a method
	# breaking changes need to be investigated
	# We can also bump python to 3.12 in Dockerfile with this update
	"aiomqtt==1.2.1",
	"pytimeparse",
]

[project.optional-dependencies]
test = [
	"pytest",
	"pytest-asyncio",
	"sanic-testing",
	"mypy",
	"types-ujson",
]

[tool.mypy]
[[tool.mypy.overrides]]
module = "mypy-sanic_ext.*"
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "--doctest-modules -p no:cacheprovider"
