name: ApiEdit

on:
  push:
    paths:
      - "api_edit/**"
      - ".github/workflows/api_edit.yml"

jobs:
  publish:
    name: Docker Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Test
        working-directory: api_edit
        run: docker build --target test .
      - name: Build
        working-directory: api_edit
        run: docker build --target production .
