name: Browser2

on:
  push:
    paths:
    - 'browser2/**'
    - '.github/workflows/browser2.yml'

jobs:
  publish:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build .
      working-directory: browser2
