name: Browser2

on:
  push:
    paths:
    - 'browser2/**'

jobs:
  publish:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: karakara/browser2
        workdir: browser2
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
