name: Push Nginx

on:
  push:
    paths:
    - 'nginx/**'

jobs:
  build:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: karakara/nginx
		dockerfile: nginx/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
