name: ProcessMedia3

on:
  push:
    paths:
    - 'processmedia3/**'
    - '.github/workflows/processmedia3.yml'

jobs:
  publish:
    name: Docker Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: docker build --target test .
      working-directory: processmedia3
    - name: Build
      run: docker build --target production .
      working-directory: processmedia3
