name: Cypress Browser Tests

on: [workflow_dispatch]
# Disable running on every commit because this job downloaded a 4gb image and github actions have no cache
# on:
#   push:
#     paths:
#       - 'cypress.json'
#       - 'cypress/**'
#       - 'app/**'

jobs:

  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: make test_cypress_run

      - name: Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
            #name: cypress artifacts
            path: test_cypress/reports/

  # cypress-run:
  #   runs-on: ubuntu-24.04
  #   container: cypress/included:9.4.1
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - run: cypress run
  #       env:
  #         CYPRESS_BASE_URL: 'http://localhost:8000/'
